// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frybvzdlijdcdixstzwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyeWJ2emRsaWpkY2RpeHN0endmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTU0ODcsImV4cCI6MjA2OTg3MTQ4N30.eQw5w8VT56vUmrMA0yB6J0mdCwoHEwdRkgOUau6DB4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});